version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8617
      POSTGRES_DB: stock_data_read
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:8617@db:5432/stock_data_read
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: